In [ ]:
import pandas as pd
import csv
import requests
from bs4 import BeautifulSoup

Books_details = []

def main_code():
  for page_num in range(1 , 6):
    url = f'https://books.toscrape.com/catalogue/page-{page_num}.html'
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('li', class_='col-xs-6 col-sm-4 col-md-3 col-lg-3')

    for index , book in enumerate(books , 1) :
      # id => index
      book_name = book.find('h3').find('a')['title']
      book_rate = book.find('p', class_ = 'star-rating')['class'][1]
      book_price = book.find('p', class_ = 'price_color').text
      book_link = book.find('a')['href']
      # book_auther =
      # publishdate =

      Books_details.append({
      'Id' : index ,
      'Name' : book_name ,
      'Rate_Stars' : book_rate ,
      'Price'  : book_price ,
      'Link ' : book_link
      #    'Auther'  : book_auther
      #    'publishdate' : publishdate

      })

def csv_printing():
  header = Books_details[0].keys()
  path = 'Book_Fair_collected.csv'
  with open(path,'w', newline ='') as File :
    writer = csv.DictWriter(File , header)
    writer.writeheader()
    writer.writerows(Books_details)
    print ('File made successfully')

main_code()
csv_printing()

File made successfully

**Activity 1 tasks** :
* step 1 - read_csv **(Done)** , run df.head() **(Done)**
* step 2 - run .info() **(Done)** - run .isnull().sum() to locate any missing API data **( ? )**
* step 3 - Fil missing author names with "unknown" **( ? )** - missing publish year with column median **( ? )**
* step 4 -  calculate average price per rating **(Done)** - correlation between prices & publish year **( ? )**

**Activity 2 tasks** :
* step 1 - import cleaned csv using read_csv **(Done)** - confirm missing values **(Done)**
* step 2 - groupby rating_stares with price to detect influence with mean
* step 3 - run correlation between price and publish_year **(Done in ac 1 step 4 )**
* step 4 - synthesize findings ( scatter plot ) + recommendation for the manager ( Insight )

-----------------------------------
# Activity 1
-----------------------------------

# Step 1 - Reload

In [ ]:
df = pd.read_csv('/content/Book_Fair_collected.csv')
print ("Data is loaded ! ")

print ("Shape : ", df.shape)
print()

print ("First 5 rows : ")
print(df.head())

Data is loaded !
Shape :  (100, 5)

First 5 rows :
   Id                                   Name Rate_Stars    Price  \
0   1                   A Light in the Attic      Three  Â£51.77
1   2                     Tipping the Velvet        One  Â£53.74
2   3                             Soumission        One  Â£50.10
3   4                          Sharp Objects       Four  Â£47.82
4   5  Sapiens: A Brief History of Humankind       Five  Â£54.23

                                               Link
0               a-light-in-the-attic_1000/index.html
1                  tipping-the-velvet_999/index.html
2                          soumission_998/index.html
3                       sharp-objects_997/index.html
4  sapiens-a-brief-history-of-humankind_996/index...

# Step 2 - Diagnostics

In [ ]:
print("Missing_values & Data_types : ")
print(df.info())

Missing_values & Data_types :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          100 non-null    int64
 1   Name        100 non-null    object
 2   Rate_Stars  100 non-null    object
 3   Price       100 non-null    object
 4   Link        100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB
None

In [ ]:
print("Statistical summary : ")
print(df.describe())

Statistical summary :
               Id
count  100.000000
mean    10.500000
std      5.795331
min      1.000000
25%      5.750000
50%     10.500000
75%     15.250000
max     20.000000

**Problems Founded**

---
1. Rate is a string so we have to transform it to number ( integers ) to make operations like calculate the average
2. Price appeared as object ( Same problem of rate )

# Step 3 - cleaning

In [ ]:
# view values of rate column
print(df['Rate_Stars'].unique())

['Three' 'One' 'Four' 'Five' 'Two']

In [ ]:
# Handle Rate format - transform rate to integers
integers = {
    'One' : 1 ,
    'Two' : 2 ,
    'Three' : 3 ,
    'Four' : 4 ,
    'Five' : 5
}
df['Rate_Stars']= df['Rate_Stars'].replace(integers)

/tmp/ipykernel_684/51857259.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Rate_Stars']= df['Rate_Stars'].replace(integers)

In [ ]:
# Delete Â£ from prices column & transform price to numbers
df['Price']= df['Price'].str.replace("Â£","").astype(float)

# Step 4 - statistical analysis

In [ ]:
# calculate average price per rating
df.groupby('Rate_Stars')['Price'].mean()

Rate_Stars
1    35.519545
2    35.909474
3    36.839091
4    33.981667
5    30.012105
Name: Price, dtype: float64

In [ ]:
# Save clean file
df.to_csv('Book_Fair_collected-clean.csv', index = False)
print("Cleaned Data Saved")

Cleaned Data Saved

-----------------------------------
# Activity 2
-----------------------------------

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Book_Fair_collected-clean.csv')
print ("cleaned Shape : " , df.shape)

# confirm missing values
df.isna().sum()

cleaned Shape :  (100, 5)

Id            0
Name          0
Rate_Stars    0
Price         0
Link          0
dtype: int64